#!/usr/bin/env bash

# http://opencircuitdesign.com/qflow/

set -eu

sudo apt-get install libffi-dev libgsl-dev

mkdir -p qflow
cd qflow

git clone https://github.com/cliffordwolf/yosys
cd yosys
make -j"$(nproc)"
sudo make install
cd ..

git clone https://github.com/rubund/graywolf
cd graywolf
# https://github.com/rubund/graywolf/pull/15
patch -f -p1 <../../graywolf-cfree.patch
cmake .
# https://github.com/rubund/graywolf/issues/18
#make -j"$(nproc)"
make
sudo make install
cd ..

# Latest version not working.
#git clone git://opencircuitdesign.com/qrouter-1.4
#cd qrouter-1.4
git clone git://opencircuitdesign.com/qrouter-1.3
cd qrouter-1.3
./configure
make -j"$(nproc)"
sudo make install
cd ..

git clone git://opencircuitdesign.com/magic-8.2
cd magic-8.2
./configure
make -j"$(nproc)"
sudo make install
cd ..

#git clone git://opencircuitdesign.com/qflow-1.2
#cd qflow-1.2
git clone git://opencircuitdesign.com/qflow-1.1
cd qflow-1.1
./configure \
  --with-graywolf="$(which graywolf)" \
  --with-magic="$(which magic)" \
  --with-qrouter="$(which qrouter)" \
  --with-yosys="$(which yosys)" \
;
make -j"$(nproc)"
sudo make install
cd ..

mkdir qflow-demo
cd qflow-demo
wget \
  http://opencircuitdesign.com/qflow/example/load.tcl \
  http://opencircuitdesign.com/qflow/example/map9v3.cel2 \
  http://opencircuitdesign.com/qflow/example/map9v3.tcl \
  http://opencircuitdesign.com/qflow/example/map9v3.v \
  http://opencircuitdesign.com/qflow/example/map9v3_cosim_tb.spi \
  http://opencircuitdesign.com/qflow/example/map9v3_gates_tb.v \
  http://opencircuitdesign.com/qflow/example/osu035_stdcells.gds2 \
  http://opencircuitdesign.com/qflow/example/osu035_stdcells.v \
  http://opencircuitdesign.com/qflow/example/setup.tcl \
;
mkdir -p layout source synthesis
cp map9v3.v source
#qflow synthesize place route sta map9v3
